
// Copyright (c) 2026 Paul Guénette
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

/**
 * @file wet_trig.hpp
 * @brief Fast float sine and cosine with full-range wrapping
 *
 * Minimax polynomial approximations for sin/cos using nearbyint-based
 * range reduction.  Accepts any float input (not restricted to [0, 2pi]).
 *
 * Range reduction normalizes any angle x to g in [-0.5, 0.5] via:
 *
 *     n = nearbyint(x / pi)
 *     g = x / pi - n            (g is in half-periods)
 *
 * Then a single degree-7 minimax polynomial evaluates sin(pi*g):
 *
 *     sin(x)  = (-1)^n * sin(pi*g)
 *     cos(x)  = sin(x + pi/2)
 *     sincos  = one reduce, two poly evals via sin(pi*g) and sin(pi*(0.5-g))
 *
 * Accuracy: ~8 ULP max for float (comparable to TI ARM trig).
 * Performance: branchless, 17 instructions for sin on Cortex-M7.
 *
 * @note Compare with TI ARM's ti_arm::sin / ti_arm::cos which are
 *       restricted to [0, 2pi] and use manual quadrant branching.
 *
 * @see "Minimax Approximations" in Hart et al., "Computer Approximations" (1968)
 * @see analysis/minimax_trig.py for coefficient generation
 *
 * Example:
 * @code
 * #include "wet_trig.hpp"
 *
 * // Works for any angle — no manual wrapping needed
 * float s = wet::sin(3.7f);
 * float c = wet::cos(-100.0f);
 *
 * // sincos is cheaper than calling sin + cos separately
 * auto [sin_val, cos_val] = wet::sincos(angle);
 * @endcode
 */
#pragma once

#include <cmath>
#include <cstddef>
#include <numbers>

namespace wet::detail {

constexpr float sin_coeffs[] = {
    +3.141582250595093e+0f,
    -5.167152404785156e+0f,
    +2.541962385177612e+0f,
    -5.547642707824707e-1f,
};

constexpr float asin_coeffs[] = {
    +1.5707954168319702f,
    -0.21451792120933533f,
    +0.087919704616069794f,
    -0.045087486505508423f,
    +0.01950908824801445f,
    -0.0044070659205317497f,
};

constexpr float atan_coeffs[] = {
    +4.17232513427734375e-7f,
    +0.99997341632843017578125f,
    +1.46687030792236328125e-4f,
    -0.330976545810699462890625f,
    -2.6895701885223388671875e-2f,
    +0.309777557849884033203125f,
    -0.21780431270599365234375f,
    +5.117702484130859375e-2f,
};

/**
 * @brief Decomposition of x = pi * (period_index + frac), frac in [-0.5, 0.5]
 *
 * Only the parity bit of period_index is needed at runtime to recover
 * sin/cos via sin(x) = (-1)^period_index * sin(pi*frac).
 */
struct Reduced {
    float frac;
    int   period_index;
};

constexpr Reduced wrap(float x, float phase_shift = 0.0f);
constexpr float   sin_poly(float frac);

template<size_t N>
constexpr float horner_eval(float x, const float (&coeffs)[N]);

} // namespace wet::detail

namespace wet {

/**
 * @brief Sine of an angle in radians
 *
 * Accepts any float; ~8 ULP accuracy.
 *
 * @param angle_rad  Angle in radians
 * @return sin(angle_rad)
 */
constexpr float sin(float angle_rad) {
    auto [frac, period_index] = detail::wrap(angle_rad);
    float s = detail::sin_poly(frac);

    return (period_index & 1) ? -s : s;
}

/**
 * @brief Cosine of an angle in radians
 *
 * cos(x) = sin(x + pi/2), with the pi/2 shift folded into wrap's FMA.
 *
 * @param angle_rad  Angle in radians
 * @return cos(angle_rad)
 */
constexpr float cos(float angle_rad) {
    auto [frac, period_index] = detail::wrap(angle_rad, 0.5f);
    float c = detail::sin_poly(frac);

    return (period_index & 1) ? -c : c;
}

struct SinCosResult {
    float sin;
    float cos;
};

/**
 * @brief Paired sin/cos from a single range reduction
 *
 * cos(pi*frac) = sin(pi*(0.5 - |frac|)); the fabs keeps the cos polynomial
 * argument in [0, 0.5] where the fit is valid.
 *
 * @param angle_rad  Angle in radians
 * @return SinCosResult{sin, cos}
 */
constexpr SinCosResult sincos(float angle_rad) {
    auto [frac, period_index] = detail::wrap(angle_rad);

    float s = detail::sin_poly(frac);
    float c = detail::sin_poly(0.5f - std::fabs(frac));

    if (period_index & 1) {
        s = -s;
        c = -c;
    }

    return {s, c};
}

/**
 * @brief Arcsine, x in [-1, 1], result in [-pi/2, pi/2]
 *
 * @param x  Input in [-1, 1] (clamped if outside)
 * @return asin(x)
 */
constexpr float asin(float x) {
    bool negate = false;

    if (x < 0.0f) {
        x = -x;
        negate = true;
    }

    if (x > 1.0f) {
        x = 1.0f;
    }

    float sqrt_1_minus_x = std::sqrt(1.0f - x);
    float p = detail::horner_eval(x, detail::asin_coeffs);
    float result = std::numbers::pi_v<float> / 2.0f - sqrt_1_minus_x * p;

    return negate ? -result : result;
}

/**
 * @brief Arccosine, x in [-1, 1], result in [0, pi]
 *
 * @param x  Input in [-1, 1] (clamped if outside)
 * @return acos(x)
 */
constexpr float acos(float x) {
    bool negate = false;

    if (x < 0.0f) {
        x = -x;
        negate = true;
    }

    if (x > 1.0f) {
        x = 1.0f;
    }

    float sqrt_1_minus_x = std::sqrt(1.0f - x);
    float p = detail::horner_eval(x, detail::asin_coeffs);
    float result = std::numbers::pi_v<float> / 2.0f - sqrt_1_minus_x * p;

    return negate ? (std::numbers::pi_v<float> - result) : result;
}

/**
 * @brief Arctangent, any float, result in [-pi/2, pi/2]
 *
 * |x| > 1 reduced via atan(x) = pi/2 - atan(1/x).
 *
 * @param x  Input value
 * @return atan(x)
 */
constexpr float atan(float x) {
    bool negate = false;
    bool complement = false;

    if (x < 0.0f) {
        x = -x;
        negate = true;
    }

    if (std::abs(x) > 1.0f) {
        x = 1.0f / x;
        complement = true;
    }

    float result = detail::horner_eval(x, detail::atan_coeffs);

    if (complement) {
        result = std::numbers::pi_v<float> / 2.0f - result;
    }

    return negate ? -result : result;
}

/**
 * @brief Two-argument arctangent, result in [-pi, pi]
 *
 * Polynomial is fit on [0, 1]; min/max + sign tricks fold all four quadrants
 * onto that interval.
 *
 * @param y  Y-coordinate
 * @param x  X-coordinate
 * @return atan2(y, x)
 */
constexpr float atan2(float y, float x) {
    float ax = std::fabs(x);
    float ay = std::fabs(y);
    float lo = std::fmin(ax, ay);
    float hi = std::fmax(ax, ay);
    float t = detail::horner_eval(lo / hi, detail::atan_coeffs);

    float r = (ay > ax) ? (std::numbers::pi_v<float> / 2.0f - t) : t;
    r = (x >= 0.0f) ? r : (std::numbers::pi_v<float> - r);

    return std::copysign(r, y);
}

} // namespace wet

namespace wet::detail {

/**
 * @brief Wrap any angle (radians) into the polynomial's input domain
 *
 * phase_shift offsets the fractional part in half-period units; cos uses
 * 0.5 to fold pi/2 into the same FMA.  No Cody-Waite split -- single-
 * precision cancellation at large |x| is within the ~8 ULP target.
 *
 * @param x            Angle in radians
 * @param phase_shift  Constant offset in half-periods (0 for sin, 0.5 for cos)
 * @return Reduced{frac, period_index}
 */
constexpr Reduced wrap(float x, float phase_shift) {
    float half_periods = x * std::numbers::inv_pi_v<float> + phase_shift;
    float nearest_period = std::nearbyint(half_periods);
    int   period_index = static_cast<int>(nearest_period);
    float frac = half_periods - nearest_period;

    return {frac, period_index};
}

/**
 * @brief Evaluate sin(pi*frac) using the degree-7 minimax polynomial
 *
 * sin(pi*frac) = frac * (c0 + c1*u + c2*u^2 + c3*u^3) with u = frac^2.
 * Precomputing u^2 lets GCC reorganize the FMAs as an even/odd split
 * for pipeline ILP; clang stays in Horner form.
 *
 * @param frac  Fractional half-period in [-0.5, 0.5]
 * @return sin(pi * frac)
 */
constexpr float sin_poly(float frac) {
    float u = frac * frac;
    float u2 = u * u;

    float p = sin_coeffs[0];
    p += sin_coeffs[1] * u;
    p += sin_coeffs[2] * u2;
    p += sin_coeffs[3] * u2 * u;

    return frac * p;
}

/**
 * @brief Horner evaluation of a polynomial in float32
 *
 * Generic polynomial evaluator: p = coeffs[0] + x * (coeffs[1] + x * (...))
 * Compiles to a chain of FMA instructions on FPU architectures.
 *
 * @param x       Evaluation point
 * @param coeffs  Polynomial coefficients, lowest power first
 * @return p(x)
 */
template<size_t N>
constexpr float horner_eval(float x, const float (&coeffs)[N]) {
    static_assert(N >= 1, "horner_eval requires at least one coefficient");
    float p = coeffs[N - 1];
    for (int i = static_cast<int>(N) - 2; i >= 0; --i) {
        p = coeffs[i] + (x * p);
    }
    return p;
}

} // namespace wet::detail
