#include "wet_trig.hpp"

#include <cmath>
#include <numbers>

namespace {

/**
 * Minimax coefficients for sin(pi*frac) ~= frac * P(frac^2), frac in [-0.5, 0.5].
 *
 *     sin(pi*frac) = frac * (c0 + c1*u + c2*u^2 + c3*u^3),  u = frac^2
 *
 * Degree 7 overall (4 coefficients).  Max absolute error ~8e-7 (~7 ULP).
 * Generated by analysis/minimax_trig.py:
 *   1. Direct LP fit minimizing max |sin(pi*frac) - frac*P(frac^2)| over
 *      frac in [-0.5, 0.5].  NOT the sinc form |sin(pi*frac)/frac - P(frac^2)|,
 *      which over-weights small |frac| (where errors barely affect the output).
 *   2. Iterative float32-aware rounding: round one coefficient at a time and
 *      re-solve the LP to absorb the rounding error in the remaining free
 *      coefficients.  Recovers ~2% accuracy vs naive round-after-fit.
 *
 * The values approximate scaled Taylor terms (Taylor would give c0=pi,
 * c1=-pi^3/6, etc.) but the minimax solver shifts them to equioscillate
 * the residual error across the domain.
 */
constexpr float sin_coeffs[] = {
    +3.141582250595093e+0f, // ~ pi
    -5.167152404785156e+0f, // ~ -pi^3/6
    +2.541962385177612e+0f, // ~  pi^5/120
    -5.547642707824707e-1f, // ~ -pi^7/5040
};

/**
 * Minimax coefficients for asin(x) on [0, 1].
 *
 * Uses the form: asin(x) = π/2 - √(1-x) * P(x)
 * P(x) = c0 + c1*x + c2*x^2 + ... + c5*x^5 (degree-5 polynomial)
 *
 * Generated by analysis/minimax_trig.py with careful numerical handling in double precision.
 * Fitting is done on [0, 0.99] with Taylor expansion handling near x=1.
 * Max absolute error: ~1.1e-6 (~5-6 ULP)
 */
constexpr float asin_coeffs[] = {
    +1.5707954168319702f,    // c0
    -0.21451792120933533f,   // c1
    +0.087919704616069794f,  // c2
    -0.045087486505508423f,  // c3
    +0.01950908824801445f,   // c4
    -0.0044070659205317497f, // c5
};

/**
 * Minimax coefficients for atan(x) on [0, 1].
 *
 * Uses a direct polynomial: atan(x) = P(x)
 * P(x) = c0 + c1*x + c2*x^2 + ... + c7*x^7 (degree-7 polynomial)
 *
 * Generated by analysis/minimax_trig.py with float32-aware iterative rounding.
 * Max absolute error ~1e-6 (~5-6 ULP).
 */
constexpr float atan_coeffs[] = {
    +4.17232513427734375e-7f,
    +0.99997341632843017578125f,
    +1.46687030792236328125e-4f,
    -0.330976545810699462890625f,
    -2.6895701885223388671875e-2f,
    +0.309777557849884033203125f,
    -0.21780431270599365234375f,
    +5.117702484130859375e-2f,
};

/**
 * @brief Result of range-reducing an angle to the polynomial's input domain
 *
 * Any angle x can be written as x = pi * (period_index + frac), where
 * frac is the fractional half-period in [-0.5, 0.5].  The polynomial
 * evaluates sin(pi*frac); the period_index tells us how to recover the
 * full-range sin(x) value:
 *
 *     sin(x) = (-1)^period_index * sin(pi * frac)
 *
 * In code, we only need the parity bit (period_index & 1).
 */
struct Reduced {
    float frac;         ///< Fractional half-period in [-0.5, 0.5]
    int   period_index; ///< Integer half-period count; odd parity flips sign
};

/**
 * @brief Wrap any angle (radians) into the polynomial's input domain
 *
 * Expresses x as `pi * (period_index + frac)` where frac is in [-0.5, 0.5].
 * The optional `phase_shift` parameter offsets the fractional part by a
 * constant amount in half-periods -- used by cos(x), which is sin(x + pi/2)
 * and so wants a 0.5 half-period shift folded into the same FMA.
 *
 * Implementation:
 *   1. Convert radians to half-periods:  half_periods = x / pi + phase_shift
 *      Combined with the shift into a single FMA (one instruction).
 *   2. Round to the nearest integer half-period using nearbyint (compiles to
 *      VRINTR on Cortex-M) -- branchless, no quadrant if/else needed.
 *   3. The remainder after rounding is in [-0.5, 0.5] by construction.
 *
 * No Cody-Waite split: single-precision cancellation noise (a few ULP at
 * the extremes of large |x|) is acceptable for the ~8 ULP target.
 */
inline Reduced reduce(float x, float phase_shift = 0.0f) {
    float half_periods = x * std::numbers::inv_pi_v<float> + phase_shift;
    float nearest_period = std::nearbyint(half_periods);
    int   period_index = static_cast<int>(nearest_period);
    float frac = half_periods - nearest_period;
    return {frac, period_index};
}

/**
 * @brief Evaluate sin(pi*frac) using the degree-7 minimax polynomial
 *
 * Horner-style accumulation in u = frac^2.  The polynomial is odd, so we
 * factor out frac and evaluate a polynomial in u:
 *
 *     sin(pi*frac) = frac * (c0 + c1*u + c2*u^2 + c3*u^3)
 *
 * Written as a += chain because the compiler generates the same FMA chain
 * as nested Horner form, but the source reads naturally as a "polynomial
 * accumulator" rather than nested parentheses.
 */
inline float sin_poly(float frac) {
    float u = frac * frac;
    float u2 = u * u;

    float p = sin_coeffs[0];
    p += sin_coeffs[1] * u;
    p += sin_coeffs[2] * u2;
    p += sin_coeffs[3] * u2 * u;

    return frac * p;
}

/**
 * @brief Horner evaluation of a polynomial in float32
 *
 * Generic polynomial evaluator: p = coeffs[0] + x * (coeffs[1] + x * (...))
 * Compiles to a chain of FMA instructions on FPU architectures.
 */
template<size_t N>
inline float horner_eval(float x, const float (&coeffs)[N]) {
    static_assert(N >= 1, "horner_eval requires at least one coefficient");
    float p = coeffs[N - 1];
    for (int i = static_cast<int>(N) - 2; i >= 0; --i) {
        p = coeffs[i] + (x * p);
    }
    return p;
}

} // namespace

namespace wet {

float sin(float angle_rad) {
    auto [frac, period_index] = reduce(angle_rad);
    float s = sin_poly(frac);
    return (period_index & 1) ? -s : s;
}

float cos(float angle_rad) {
    // cos(x) = sin(x + pi/2).  The 0.5 phase_shift adds pi/2 in half-period
    // units -- folded into the reduce FMA for free (no separate VADD).
    auto [frac, period_index] = reduce(angle_rad, 0.5f);
    float c = sin_poly(frac);
    return (period_index & 1) ? -c : c;
}

SinCosResult sincos(float angle_rad) {
    auto [frac, period_index] = reduce(angle_rad);

    // Compute both sin and cos from a single reduction:
    //   sin(pi*frac) = frac * P(frac^2)       -- direct from polynomial
    //   cos(pi*frac) = sin(pi*(0.5 - |frac|)) -- cos is even, so cos(pi*frac) =
    //                                            cos(pi*|frac|), and the shift
    //                                            keeps the polynomial argument
    //                                            in [0, 0.5] where it's valid.
    float s = sin_poly(frac);
    float c = sin_poly(0.5f - std::fabs(frac));

    if (period_index & 1) {
        s = -s;
        c = -c;
    }
    return {s, c};
}

float asin(float x) {
    bool negate = false;

    if (x < 0.0f) {
        x = -x;
        negate = true;
    }

    // Clamp to [0, 1] to avoid NaN from sqrt
    if (x > 1.0f) {
        x = 1.0f;
    }

    float sqrt_1_minus_x = std::sqrt(1.0f - x);
    float p = horner_eval(x, asin_coeffs);
    float result = std::numbers::pi_v<float> / 2.0f - sqrt_1_minus_x * p;

    if (negate) {
        result = -result;
    }

    return result;
}

float acos(float x) {
    bool negate = false;

    if (x < 0.0f) {
        x = -x;
        negate = true;
    }

    // Clamp to [0, 1] to avoid NaN from sqrt
    if (x > 1.0f) {
        x = 1.0f;
    }

    float sqrt_1_minus_x = std::sqrt(1.0f - x);
    float p = horner_eval(x, asin_coeffs);
    float result = std::numbers::pi_v<float> / 2.0f - sqrt_1_minus_x * p;

    if (negate) {
        result = std::numbers::pi_v<float> - result;
    }

    return result;
}

float atan(float x) {
    bool negate = false;
    bool complement = false;

    if (x < 0.0f) {
        x = -x;
        negate = true;
    }

    if (std::abs(x) > 1.0f) {
        x = 1.0f / x;
        complement = true;
    }

    float result = horner_eval(x, atan_coeffs);

    if (complement) {
        result = std::numbers::pi_v<float> / 2.0f - result;
    }
    if (negate) {
        result = -result;
    }

    return result;
}

float atan2(float y, float x) {
    float ax = std::fabs(x);
    float ay = std::fabs(y);
    float lo = std::fmin(ax, ay);
    float hi = std::fmax(ax, ay);
    float t = horner_eval(lo / hi, atan_coeffs);

    // Complement if |y| > |x|: full angle is pi/2 - atan(lo/hi)
    float r = (ay > ax) ? (std::numbers::pi_v<float> / 2.0f - t) : t;

    // Left half-plane: pi - r
    r = (x >= 0.0f) ? r : (std::numbers::pi_v<float> - r);

    // Apply sign of y
    return std::copysign(r, y);
}

} // namespace wet
